-- =====================================================
-- Sankofa Enterprise Pro - Database Schema Reference
-- =====================================================
--
-- NOTA: Este arquivo foi consolidado com o schema principal.
--
-- O schema completo e oficial está localizado em:
--   DB/schema.sql (versão 12.0)
--
-- O schema principal inclui:
--   - Todas as tabelas (transactions, fraud_detections, customers, etc.)
--   - Índices otimizados para performance
--   - Triggers para atualização automática
--   - Views para estatísticas
--   - Extensões necessárias (uuid-ossp, pgcrypto, pg_trgm)
--   - Documentação completa
--
-- Para executar migrations, use:
--   DB/migrations/001_initial_schema.sql
--
-- CORRECAO 10/10: Schema consolidado para evitar conflitos
-- =====================================================

-- Redireciona para o schema principal
\i '../../../DB/schema.sql'
